// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package medizin.server.domain;

import java.util.List;
import medizin.server.domain.AnswerToAssQuestion;
import medizin.server.domain.AnswerToAssQuestionDataOnDemand;
import medizin.server.domain.AnswerToAssQuestionIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AnswerToAssQuestionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AnswerToAssQuestionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AnswerToAssQuestionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AnswerToAssQuestionIntegrationTest: @Transactional;
    
    @Autowired
    private AnswerToAssQuestionDataOnDemand AnswerToAssQuestionIntegrationTest.dod;
    
    @Test
    public void AnswerToAssQuestionIntegrationTest.testCountAnswerToAssQuestions() {
        Assert.assertNotNull("Data on demand for 'AnswerToAssQuestion' failed to initialize correctly", dod.getRandomAnswerToAssQuestion());
        long count = AnswerToAssQuestion.countAnswerToAssQuestions();
        Assert.assertTrue("Counter for 'AnswerToAssQuestion' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AnswerToAssQuestionIntegrationTest.testFindAnswerToAssQuestion() {
        AnswerToAssQuestion obj = dod.getRandomAnswerToAssQuestion();
        Assert.assertNotNull("Data on demand for 'AnswerToAssQuestion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AnswerToAssQuestion' failed to provide an identifier", id);
        obj = AnswerToAssQuestion.findAnswerToAssQuestion(id);
        Assert.assertNotNull("Find method for 'AnswerToAssQuestion' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'AnswerToAssQuestion' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AnswerToAssQuestionIntegrationTest.testFindAllAnswerToAssQuestions() {
        Assert.assertNotNull("Data on demand for 'AnswerToAssQuestion' failed to initialize correctly", dod.getRandomAnswerToAssQuestion());
        long count = AnswerToAssQuestion.countAnswerToAssQuestions();
        Assert.assertTrue("Too expensive to perform a find all test for 'AnswerToAssQuestion', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<AnswerToAssQuestion> result = AnswerToAssQuestion.findAllAnswerToAssQuestions();
        Assert.assertNotNull("Find all method for 'AnswerToAssQuestion' illegally returned null", result);
        Assert.assertTrue("Find all method for 'AnswerToAssQuestion' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AnswerToAssQuestionIntegrationTest.testFindAnswerToAssQuestionEntries() {
        Assert.assertNotNull("Data on demand for 'AnswerToAssQuestion' failed to initialize correctly", dod.getRandomAnswerToAssQuestion());
        long count = AnswerToAssQuestion.countAnswerToAssQuestions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<AnswerToAssQuestion> result = AnswerToAssQuestion.findAnswerToAssQuestionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'AnswerToAssQuestion' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'AnswerToAssQuestion' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AnswerToAssQuestionIntegrationTest.testFlush() {
        AnswerToAssQuestion obj = dod.getRandomAnswerToAssQuestion();
        Assert.assertNotNull("Data on demand for 'AnswerToAssQuestion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AnswerToAssQuestion' failed to provide an identifier", id);
        obj = AnswerToAssQuestion.findAnswerToAssQuestion(id);
        Assert.assertNotNull("Find method for 'AnswerToAssQuestion' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAnswerToAssQuestion(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'AnswerToAssQuestion' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AnswerToAssQuestionIntegrationTest.testMergeUpdate() {
        AnswerToAssQuestion obj = dod.getRandomAnswerToAssQuestion();
        Assert.assertNotNull("Data on demand for 'AnswerToAssQuestion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AnswerToAssQuestion' failed to provide an identifier", id);
        obj = AnswerToAssQuestion.findAnswerToAssQuestion(id);
        boolean modified =  dod.modifyAnswerToAssQuestion(obj);
        Integer currentVersion = obj.getVersion();
        AnswerToAssQuestion merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'AnswerToAssQuestion' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AnswerToAssQuestionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'AnswerToAssQuestion' failed to initialize correctly", dod.getRandomAnswerToAssQuestion());
        AnswerToAssQuestion obj = dod.getNewTransientAnswerToAssQuestion(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'AnswerToAssQuestion' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'AnswerToAssQuestion' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'AnswerToAssQuestion' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AnswerToAssQuestionIntegrationTest.testRemove() {
        AnswerToAssQuestion obj = dod.getRandomAnswerToAssQuestion();
        Assert.assertNotNull("Data on demand for 'AnswerToAssQuestion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AnswerToAssQuestion' failed to provide an identifier", id);
        obj = AnswerToAssQuestion.findAnswerToAssQuestion(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'AnswerToAssQuestion' with identifier '" + id + "'", AnswerToAssQuestion.findAnswerToAssQuestion(id));
    }
    
}
