// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package medizin.server.domain;

import java.util.List;
import medizin.server.domain.Assesment;
import medizin.server.domain.AssesmentDataOnDemand;
import medizin.server.domain.AssesmentIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AssesmentIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AssesmentIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AssesmentIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AssesmentIntegrationTest: @Transactional;
    
    @Autowired
    private AssesmentDataOnDemand AssesmentIntegrationTest.dod;
    
    @Test
    public void AssesmentIntegrationTest.testCountAssesments() {
        Assert.assertNotNull("Data on demand for 'Assesment' failed to initialize correctly", dod.getRandomAssesment());
        long count = Assesment.countAssesments();
        Assert.assertTrue("Counter for 'Assesment' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AssesmentIntegrationTest.testFindAssesment() {
        Assesment obj = dod.getRandomAssesment();
        Assert.assertNotNull("Data on demand for 'Assesment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Assesment' failed to provide an identifier", id);
        obj = Assesment.findAssesment(id);
        Assert.assertNotNull("Find method for 'Assesment' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Assesment' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AssesmentIntegrationTest.testFindAllAssesments() {
        Assert.assertNotNull("Data on demand for 'Assesment' failed to initialize correctly", dod.getRandomAssesment());
        long count = Assesment.countAssesments();
        Assert.assertTrue("Too expensive to perform a find all test for 'Assesment', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Assesment> result = Assesment.findAllAssesments();
        Assert.assertNotNull("Find all method for 'Assesment' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Assesment' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AssesmentIntegrationTest.testFindAssesmentEntries() {
        Assert.assertNotNull("Data on demand for 'Assesment' failed to initialize correctly", dod.getRandomAssesment());
        long count = Assesment.countAssesments();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Assesment> result = Assesment.findAssesmentEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Assesment' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Assesment' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AssesmentIntegrationTest.testFlush() {
        Assesment obj = dod.getRandomAssesment();
        Assert.assertNotNull("Data on demand for 'Assesment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Assesment' failed to provide an identifier", id);
        obj = Assesment.findAssesment(id);
        Assert.assertNotNull("Find method for 'Assesment' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAssesment(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Assesment' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AssesmentIntegrationTest.testMergeUpdate() {
        Assesment obj = dod.getRandomAssesment();
        Assert.assertNotNull("Data on demand for 'Assesment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Assesment' failed to provide an identifier", id);
        obj = Assesment.findAssesment(id);
        boolean modified =  dod.modifyAssesment(obj);
        Integer currentVersion = obj.getVersion();
        Assesment merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Assesment' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AssesmentIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Assesment' failed to initialize correctly", dod.getRandomAssesment());
        Assesment obj = dod.getNewTransientAssesment(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Assesment' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Assesment' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Assesment' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AssesmentIntegrationTest.testRemove() {
        Assesment obj = dod.getRandomAssesment();
        Assert.assertNotNull("Data on demand for 'Assesment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Assesment' failed to provide an identifier", id);
        obj = Assesment.findAssesment(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Assesment' with identifier '" + id + "'", Assesment.findAssesment(id));
    }
    
}
