// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package medizin.server.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import medizin.server.domain.Institution;
import medizin.server.domain.InstitutionDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect InstitutionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: InstitutionDataOnDemand: @Component;
    
    private Random InstitutionDataOnDemand.rnd = new SecureRandom();
    
    private List<Institution> InstitutionDataOnDemand.data;
    
    public Institution InstitutionDataOnDemand.getNewTransientInstitution(int index) {
        Institution obj = new Institution();
        setInstitutionName(obj, index);
        return obj;
    }
    
    public void InstitutionDataOnDemand.setInstitutionName(Institution obj, int index) {
        String institutionName = "institutionName_" + index;
        if (institutionName.length() > 60) {
            institutionName = new Random().nextInt(10) + institutionName.substring(1, 60);
        }
        obj.setInstitutionName(institutionName);
    }
    
    public Institution InstitutionDataOnDemand.getSpecificInstitution(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Institution obj = data.get(index);
        Long id = obj.getId();
        return Institution.findInstitution(id);
    }
    
    public Institution InstitutionDataOnDemand.getRandomInstitution() {
        init();
        Institution obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Institution.findInstitution(id);
    }
    
    public boolean InstitutionDataOnDemand.modifyInstitution(Institution obj) {
        return false;
    }
    
    public void InstitutionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Institution.findInstitutionEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Institution' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Institution>();
        for (int i = 0; i < 10; i++) {
            Institution obj = getNewTransientInstitution(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
