// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package medizin.server.domain;

import java.util.List;
import medizin.server.domain.Keyword;
import medizin.server.domain.KeywordDataOnDemand;
import medizin.server.domain.KeywordIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect KeywordIntegrationTest_Roo_IntegrationTest {
    
    declare @type: KeywordIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: KeywordIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: KeywordIntegrationTest: @Transactional;
    
    @Autowired
    private KeywordDataOnDemand KeywordIntegrationTest.dod;
    
    @Test
    public void KeywordIntegrationTest.testCountKeywords() {
        Assert.assertNotNull("Data on demand for 'Keyword' failed to initialize correctly", dod.getRandomKeyword());
        long count = Keyword.countKeywords();
        Assert.assertTrue("Counter for 'Keyword' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void KeywordIntegrationTest.testFindKeyword() {
        Keyword obj = dod.getRandomKeyword();
        Assert.assertNotNull("Data on demand for 'Keyword' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Keyword' failed to provide an identifier", id);
        obj = Keyword.findKeyword(id);
        Assert.assertNotNull("Find method for 'Keyword' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Keyword' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void KeywordIntegrationTest.testFindAllKeywords() {
        Assert.assertNotNull("Data on demand for 'Keyword' failed to initialize correctly", dod.getRandomKeyword());
        long count = Keyword.countKeywords();
        Assert.assertTrue("Too expensive to perform a find all test for 'Keyword', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Keyword> result = Keyword.findAllKeywords();
        Assert.assertNotNull("Find all method for 'Keyword' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Keyword' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void KeywordIntegrationTest.testFindKeywordEntries() {
        Assert.assertNotNull("Data on demand for 'Keyword' failed to initialize correctly", dod.getRandomKeyword());
        long count = Keyword.countKeywords();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Keyword> result = Keyword.findKeywordEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Keyword' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Keyword' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void KeywordIntegrationTest.testFlush() {
        Keyword obj = dod.getRandomKeyword();
        Assert.assertNotNull("Data on demand for 'Keyword' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Keyword' failed to provide an identifier", id);
        obj = Keyword.findKeyword(id);
        Assert.assertNotNull("Find method for 'Keyword' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyKeyword(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Keyword' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void KeywordIntegrationTest.testMergeUpdate() {
        Keyword obj = dod.getRandomKeyword();
        Assert.assertNotNull("Data on demand for 'Keyword' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Keyword' failed to provide an identifier", id);
        obj = Keyword.findKeyword(id);
        boolean modified =  dod.modifyKeyword(obj);
        Integer currentVersion = obj.getVersion();
        Keyword merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Keyword' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void KeywordIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Keyword' failed to initialize correctly", dod.getRandomKeyword());
        Keyword obj = dod.getNewTransientKeyword(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Keyword' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Keyword' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Keyword' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void KeywordIntegrationTest.testRemove() {
        Keyword obj = dod.getRandomKeyword();
        Assert.assertNotNull("Data on demand for 'Keyword' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Keyword' failed to provide an identifier", id);
        obj = Keyword.findKeyword(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Keyword' with identifier '" + id + "'", Keyword.findKeyword(id));
    }
    
}
