// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package medizin.server.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import medizin.server.domain.Mc;
import medizin.server.domain.McDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect McDataOnDemand_Roo_DataOnDemand {
    
    declare @type: McDataOnDemand: @Component;
    
    private Random McDataOnDemand.rnd = new SecureRandom();
    
    private List<Mc> McDataOnDemand.data;
    
    public Mc McDataOnDemand.getNewTransientMc(int index) {
        Mc obj = new Mc();
        setMcName(obj, index);
        return obj;
    }
    
    public void McDataOnDemand.setMcName(Mc obj, int index) {
        String mcName = "mcName_" + index;
        if (mcName.length() > 50) {
            mcName = new Random().nextInt(10) + mcName.substring(1, 50);
        }
        obj.setMcName(mcName);
    }
    
    public Mc McDataOnDemand.getSpecificMc(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Mc obj = data.get(index);
        Long id = obj.getId();
        return Mc.findMc(id);
    }
    
    public Mc McDataOnDemand.getRandomMc() {
        init();
        Mc obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Mc.findMc(id);
    }
    
    public boolean McDataOnDemand.modifyMc(Mc obj) {
        return false;
    }
    
    public void McDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Mc.findMcEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Mc' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Mc>();
        for (int i = 0; i < 10; i++) {
            Mc obj = getNewTransientMc(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
