// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package medizin.server.domain;

import java.util.List;
import medizin.server.domain.Mc;
import medizin.server.domain.McDataOnDemand;
import medizin.server.domain.McIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect McIntegrationTest_Roo_IntegrationTest {
    
    declare @type: McIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: McIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: McIntegrationTest: @Transactional;
    
    @Autowired
    private McDataOnDemand McIntegrationTest.dod;
    
    @Test
    public void McIntegrationTest.testCountMcs() {
        Assert.assertNotNull("Data on demand for 'Mc' failed to initialize correctly", dod.getRandomMc());
        long count = Mc.countMcs();
        Assert.assertTrue("Counter for 'Mc' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void McIntegrationTest.testFindMc() {
        Mc obj = dod.getRandomMc();
        Assert.assertNotNull("Data on demand for 'Mc' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Mc' failed to provide an identifier", id);
        obj = Mc.findMc(id);
        Assert.assertNotNull("Find method for 'Mc' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Mc' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void McIntegrationTest.testFindAllMcs() {
        Assert.assertNotNull("Data on demand for 'Mc' failed to initialize correctly", dod.getRandomMc());
        long count = Mc.countMcs();
        Assert.assertTrue("Too expensive to perform a find all test for 'Mc', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Mc> result = Mc.findAllMcs();
        Assert.assertNotNull("Find all method for 'Mc' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Mc' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void McIntegrationTest.testFindMcEntries() {
        Assert.assertNotNull("Data on demand for 'Mc' failed to initialize correctly", dod.getRandomMc());
        long count = Mc.countMcs();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Mc> result = Mc.findMcEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Mc' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Mc' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void McIntegrationTest.testFlush() {
        Mc obj = dod.getRandomMc();
        Assert.assertNotNull("Data on demand for 'Mc' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Mc' failed to provide an identifier", id);
        obj = Mc.findMc(id);
        Assert.assertNotNull("Find method for 'Mc' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMc(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Mc' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void McIntegrationTest.testMergeUpdate() {
        Mc obj = dod.getRandomMc();
        Assert.assertNotNull("Data on demand for 'Mc' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Mc' failed to provide an identifier", id);
        obj = Mc.findMc(id);
        boolean modified =  dod.modifyMc(obj);
        Integer currentVersion = obj.getVersion();
        Mc merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Mc' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void McIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Mc' failed to initialize correctly", dod.getRandomMc());
        Mc obj = dod.getNewTransientMc(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Mc' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Mc' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Mc' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void McIntegrationTest.testRemove() {
        Mc obj = dod.getRandomMc();
        Assert.assertNotNull("Data on demand for 'Mc' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Mc' failed to provide an identifier", id);
        obj = Mc.findMc(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Mc' with identifier '" + id + "'", Mc.findMc(id));
    }
    
}
