// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package medizin.server.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import medizin.client.shared.AccessRights;
import medizin.server.domain.Person;
import medizin.server.domain.PersonDataOnDemand;
import medizin.server.domain.QuestionAccess;
import medizin.server.domain.QuestionAccessDataOnDemand;
import medizin.server.domain.QuestionDataOnDemand;
import medizin.server.domain.QuestionEventDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect QuestionAccessDataOnDemand_Roo_DataOnDemand {
    
    declare @type: QuestionAccessDataOnDemand: @Component;
    
    private Random QuestionAccessDataOnDemand.rnd = new SecureRandom();
    
    private List<QuestionAccess> QuestionAccessDataOnDemand.data;
    
    @Autowired
    private PersonDataOnDemand QuestionAccessDataOnDemand.personDataOnDemand;
    
    @Autowired
    private QuestionDataOnDemand QuestionAccessDataOnDemand.questionDataOnDemand;
    
    @Autowired
    private QuestionEventDataOnDemand QuestionAccessDataOnDemand.questionEventDataOnDemand;
    
    public QuestionAccess QuestionAccessDataOnDemand.getNewTransientQuestionAccess(int index) {
        QuestionAccess obj = new QuestionAccess();
        setAccRights(obj, index);
        setPerson(obj, index);
        return obj;
    }
    
    public void QuestionAccessDataOnDemand.setAccRights(QuestionAccess obj, int index) {
        AccessRights accRights = AccessRights.class.getEnumConstants()[0];
        obj.setAccRights(accRights);
    }
    
    public void QuestionAccessDataOnDemand.setPerson(QuestionAccess obj, int index) {
        Person person = personDataOnDemand.getRandomPerson();
        obj.setPerson(person);
    }
    
    public QuestionAccess QuestionAccessDataOnDemand.getSpecificQuestionAccess(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        QuestionAccess obj = data.get(index);
        Long id = obj.getId();
        return QuestionAccess.findQuestionAccess(id);
    }
    
    public QuestionAccess QuestionAccessDataOnDemand.getRandomQuestionAccess() {
        init();
        QuestionAccess obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return QuestionAccess.findQuestionAccess(id);
    }
    
    public boolean QuestionAccessDataOnDemand.modifyQuestionAccess(QuestionAccess obj) {
        return false;
    }
    
    public void QuestionAccessDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = QuestionAccess.findQuestionAccessEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'QuestionAccess' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<QuestionAccess>();
        for (int i = 0; i < 10; i++) {
            QuestionAccess obj = getNewTransientQuestionAccess(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
