// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package medizin.server.domain;

import java.util.List;
import medizin.server.domain.QuestionEvent;
import medizin.server.domain.QuestionEventDataOnDemand;
import medizin.server.domain.QuestionEventIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect QuestionEventIntegrationTest_Roo_IntegrationTest {
    
    declare @type: QuestionEventIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: QuestionEventIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: QuestionEventIntegrationTest: @Transactional;
    
    @Autowired
    private QuestionEventDataOnDemand QuestionEventIntegrationTest.dod;
    
    @Test
    public void QuestionEventIntegrationTest.testCountQuestionEvents() {
        Assert.assertNotNull("Data on demand for 'QuestionEvent' failed to initialize correctly", dod.getRandomQuestionEvent());
        long count = QuestionEvent.countQuestionEvents();
        Assert.assertTrue("Counter for 'QuestionEvent' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void QuestionEventIntegrationTest.testFindQuestionEvent() {
        QuestionEvent obj = dod.getRandomQuestionEvent();
        Assert.assertNotNull("Data on demand for 'QuestionEvent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QuestionEvent' failed to provide an identifier", id);
        obj = QuestionEvent.findQuestionEvent(id);
        Assert.assertNotNull("Find method for 'QuestionEvent' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'QuestionEvent' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void QuestionEventIntegrationTest.testFindAllQuestionEvents() {
        Assert.assertNotNull("Data on demand for 'QuestionEvent' failed to initialize correctly", dod.getRandomQuestionEvent());
        long count = QuestionEvent.countQuestionEvents();
        Assert.assertTrue("Too expensive to perform a find all test for 'QuestionEvent', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<QuestionEvent> result = QuestionEvent.findAllQuestionEvents();
        Assert.assertNotNull("Find all method for 'QuestionEvent' illegally returned null", result);
        Assert.assertTrue("Find all method for 'QuestionEvent' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void QuestionEventIntegrationTest.testFindQuestionEventEntries() {
        Assert.assertNotNull("Data on demand for 'QuestionEvent' failed to initialize correctly", dod.getRandomQuestionEvent());
        long count = QuestionEvent.countQuestionEvents();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<QuestionEvent> result = QuestionEvent.findQuestionEventEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'QuestionEvent' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'QuestionEvent' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void QuestionEventIntegrationTest.testFlush() {
        QuestionEvent obj = dod.getRandomQuestionEvent();
        Assert.assertNotNull("Data on demand for 'QuestionEvent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QuestionEvent' failed to provide an identifier", id);
        obj = QuestionEvent.findQuestionEvent(id);
        Assert.assertNotNull("Find method for 'QuestionEvent' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyQuestionEvent(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'QuestionEvent' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void QuestionEventIntegrationTest.testMergeUpdate() {
        QuestionEvent obj = dod.getRandomQuestionEvent();
        Assert.assertNotNull("Data on demand for 'QuestionEvent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QuestionEvent' failed to provide an identifier", id);
        obj = QuestionEvent.findQuestionEvent(id);
        boolean modified =  dod.modifyQuestionEvent(obj);
        Integer currentVersion = obj.getVersion();
        QuestionEvent merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'QuestionEvent' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void QuestionEventIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'QuestionEvent' failed to initialize correctly", dod.getRandomQuestionEvent());
        QuestionEvent obj = dod.getNewTransientQuestionEvent(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'QuestionEvent' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'QuestionEvent' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'QuestionEvent' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void QuestionEventIntegrationTest.testRemove() {
        QuestionEvent obj = dod.getRandomQuestionEvent();
        Assert.assertNotNull("Data on demand for 'QuestionEvent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QuestionEvent' failed to provide an identifier", id);
        obj = QuestionEvent.findQuestionEvent(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'QuestionEvent' with identifier '" + id + "'", QuestionEvent.findQuestionEvent(id));
    }
    
}
