// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package medizin.server.domain;

import java.util.List;
import medizin.server.domain.QuestionSumPerPerson;
import medizin.server.domain.QuestionSumPerPersonDataOnDemand;
import medizin.server.domain.QuestionSumPerPersonIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect QuestionSumPerPersonIntegrationTest_Roo_IntegrationTest {
    
    declare @type: QuestionSumPerPersonIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: QuestionSumPerPersonIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: QuestionSumPerPersonIntegrationTest: @Transactional;
    
    @Autowired
    private QuestionSumPerPersonDataOnDemand QuestionSumPerPersonIntegrationTest.dod;
    
    @Test
    public void QuestionSumPerPersonIntegrationTest.testCountQuestionSumPerpeople() {
        Assert.assertNotNull("Data on demand for 'QuestionSumPerPerson' failed to initialize correctly", dod.getRandomQuestionSumPerPerson());
        long count = QuestionSumPerPerson.countQuestionSumPerpeople();
        Assert.assertTrue("Counter for 'QuestionSumPerPerson' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void QuestionSumPerPersonIntegrationTest.testFindQuestionSumPerPerson() {
        QuestionSumPerPerson obj = dod.getRandomQuestionSumPerPerson();
        Assert.assertNotNull("Data on demand for 'QuestionSumPerPerson' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QuestionSumPerPerson' failed to provide an identifier", id);
        obj = QuestionSumPerPerson.findQuestionSumPerPerson(id);
        Assert.assertNotNull("Find method for 'QuestionSumPerPerson' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'QuestionSumPerPerson' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void QuestionSumPerPersonIntegrationTest.testFindAllQuestionSumPerpeople() {
        Assert.assertNotNull("Data on demand for 'QuestionSumPerPerson' failed to initialize correctly", dod.getRandomQuestionSumPerPerson());
        long count = QuestionSumPerPerson.countQuestionSumPerpeople();
        Assert.assertTrue("Too expensive to perform a find all test for 'QuestionSumPerPerson', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<QuestionSumPerPerson> result = QuestionSumPerPerson.findAllQuestionSumPerpeople();
        Assert.assertNotNull("Find all method for 'QuestionSumPerPerson' illegally returned null", result);
        Assert.assertTrue("Find all method for 'QuestionSumPerPerson' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void QuestionSumPerPersonIntegrationTest.testFindQuestionSumPerPersonEntries() {
        Assert.assertNotNull("Data on demand for 'QuestionSumPerPerson' failed to initialize correctly", dod.getRandomQuestionSumPerPerson());
        long count = QuestionSumPerPerson.countQuestionSumPerpeople();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<QuestionSumPerPerson> result = QuestionSumPerPerson.findQuestionSumPerPersonEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'QuestionSumPerPerson' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'QuestionSumPerPerson' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void QuestionSumPerPersonIntegrationTest.testFlush() {
        QuestionSumPerPerson obj = dod.getRandomQuestionSumPerPerson();
        Assert.assertNotNull("Data on demand for 'QuestionSumPerPerson' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QuestionSumPerPerson' failed to provide an identifier", id);
        obj = QuestionSumPerPerson.findQuestionSumPerPerson(id);
        Assert.assertNotNull("Find method for 'QuestionSumPerPerson' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyQuestionSumPerPerson(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'QuestionSumPerPerson' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void QuestionSumPerPersonIntegrationTest.testMergeUpdate() {
        QuestionSumPerPerson obj = dod.getRandomQuestionSumPerPerson();
        Assert.assertNotNull("Data on demand for 'QuestionSumPerPerson' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QuestionSumPerPerson' failed to provide an identifier", id);
        obj = QuestionSumPerPerson.findQuestionSumPerPerson(id);
        boolean modified =  dod.modifyQuestionSumPerPerson(obj);
        Integer currentVersion = obj.getVersion();
        QuestionSumPerPerson merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'QuestionSumPerPerson' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void QuestionSumPerPersonIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'QuestionSumPerPerson' failed to initialize correctly", dod.getRandomQuestionSumPerPerson());
        QuestionSumPerPerson obj = dod.getNewTransientQuestionSumPerPerson(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'QuestionSumPerPerson' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'QuestionSumPerPerson' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'QuestionSumPerPerson' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void QuestionSumPerPersonIntegrationTest.testRemove() {
        QuestionSumPerPerson obj = dod.getRandomQuestionSumPerPerson();
        Assert.assertNotNull("Data on demand for 'QuestionSumPerPerson' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QuestionSumPerPerson' failed to provide an identifier", id);
        obj = QuestionSumPerPerson.findQuestionSumPerPerson(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'QuestionSumPerPerson' with identifier '" + id + "'", QuestionSumPerPerson.findQuestionSumPerPerson(id));
    }
    
}
