// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package medizin.server.domain;

import java.util.List;
import medizin.server.domain.QuestionType;
import medizin.server.domain.QuestionTypeDataOnDemand;
import medizin.server.domain.QuestionTypeIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect QuestionTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: QuestionTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: QuestionTypeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: QuestionTypeIntegrationTest: @Transactional;
    
    @Autowired
    private QuestionTypeDataOnDemand QuestionTypeIntegrationTest.dod;
    
    @Test
    public void QuestionTypeIntegrationTest.testCountQuestionTypes() {
        Assert.assertNotNull("Data on demand for 'QuestionType' failed to initialize correctly", dod.getRandomQuestionType());
        long count = QuestionType.countQuestionTypes();
        Assert.assertTrue("Counter for 'QuestionType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void QuestionTypeIntegrationTest.testFindQuestionType() {
        QuestionType obj = dod.getRandomQuestionType();
        Assert.assertNotNull("Data on demand for 'QuestionType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QuestionType' failed to provide an identifier", id);
        obj = QuestionType.findQuestionType(id);
        Assert.assertNotNull("Find method for 'QuestionType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'QuestionType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void QuestionTypeIntegrationTest.testFindAllQuestionTypes() {
        Assert.assertNotNull("Data on demand for 'QuestionType' failed to initialize correctly", dod.getRandomQuestionType());
        long count = QuestionType.countQuestionTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'QuestionType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<QuestionType> result = QuestionType.findAllQuestionTypes();
        Assert.assertNotNull("Find all method for 'QuestionType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'QuestionType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void QuestionTypeIntegrationTest.testFindQuestionTypeEntries() {
        Assert.assertNotNull("Data on demand for 'QuestionType' failed to initialize correctly", dod.getRandomQuestionType());
        long count = QuestionType.countQuestionTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<QuestionType> result = QuestionType.findQuestionTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'QuestionType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'QuestionType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void QuestionTypeIntegrationTest.testFlush() {
        QuestionType obj = dod.getRandomQuestionType();
        Assert.assertNotNull("Data on demand for 'QuestionType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QuestionType' failed to provide an identifier", id);
        obj = QuestionType.findQuestionType(id);
        Assert.assertNotNull("Find method for 'QuestionType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyQuestionType(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'QuestionType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void QuestionTypeIntegrationTest.testMergeUpdate() {
        QuestionType obj = dod.getRandomQuestionType();
        Assert.assertNotNull("Data on demand for 'QuestionType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QuestionType' failed to provide an identifier", id);
        obj = QuestionType.findQuestionType(id);
        boolean modified =  dod.modifyQuestionType(obj);
        Integer currentVersion = obj.getVersion();
        QuestionType merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'QuestionType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void QuestionTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'QuestionType' failed to initialize correctly", dod.getRandomQuestionType());
        QuestionType obj = dod.getNewTransientQuestionType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'QuestionType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'QuestionType' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'QuestionType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void QuestionTypeIntegrationTest.testRemove() {
        QuestionType obj = dod.getRandomQuestionType();
        Assert.assertNotNull("Data on demand for 'QuestionType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QuestionType' failed to provide an identifier", id);
        obj = QuestionType.findQuestionType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'QuestionType' with identifier '" + id + "'", QuestionType.findQuestionType(id));
    }
    
}
