// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package medizin.server.domain;

import java.util.List;
import medizin.server.domain.QuestionTypeCountPerExam;
import medizin.server.domain.QuestionTypeCountPerExamDataOnDemand;
import medizin.server.domain.QuestionTypeCountPerExamIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect QuestionTypeCountPerExamIntegrationTest_Roo_IntegrationTest {
    
    declare @type: QuestionTypeCountPerExamIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: QuestionTypeCountPerExamIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: QuestionTypeCountPerExamIntegrationTest: @Transactional;
    
    @Autowired
    private QuestionTypeCountPerExamDataOnDemand QuestionTypeCountPerExamIntegrationTest.dod;
    
    @Test
    public void QuestionTypeCountPerExamIntegrationTest.testCountQuestionTypeCountPerExams() {
        Assert.assertNotNull("Data on demand for 'QuestionTypeCountPerExam' failed to initialize correctly", dod.getRandomQuestionTypeCountPerExam());
        long count = QuestionTypeCountPerExam.countQuestionTypeCountPerExams();
        Assert.assertTrue("Counter for 'QuestionTypeCountPerExam' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void QuestionTypeCountPerExamIntegrationTest.testFindQuestionTypeCountPerExam() {
        QuestionTypeCountPerExam obj = dod.getRandomQuestionTypeCountPerExam();
        Assert.assertNotNull("Data on demand for 'QuestionTypeCountPerExam' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QuestionTypeCountPerExam' failed to provide an identifier", id);
        obj = QuestionTypeCountPerExam.findQuestionTypeCountPerExam(id);
        Assert.assertNotNull("Find method for 'QuestionTypeCountPerExam' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'QuestionTypeCountPerExam' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void QuestionTypeCountPerExamIntegrationTest.testFindAllQuestionTypeCountPerExams() {
        Assert.assertNotNull("Data on demand for 'QuestionTypeCountPerExam' failed to initialize correctly", dod.getRandomQuestionTypeCountPerExam());
        long count = QuestionTypeCountPerExam.countQuestionTypeCountPerExams();
        Assert.assertTrue("Too expensive to perform a find all test for 'QuestionTypeCountPerExam', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<QuestionTypeCountPerExam> result = QuestionTypeCountPerExam.findAllQuestionTypeCountPerExams();
        Assert.assertNotNull("Find all method for 'QuestionTypeCountPerExam' illegally returned null", result);
        Assert.assertTrue("Find all method for 'QuestionTypeCountPerExam' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void QuestionTypeCountPerExamIntegrationTest.testFindQuestionTypeCountPerExamEntries() {
        Assert.assertNotNull("Data on demand for 'QuestionTypeCountPerExam' failed to initialize correctly", dod.getRandomQuestionTypeCountPerExam());
        long count = QuestionTypeCountPerExam.countQuestionTypeCountPerExams();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<QuestionTypeCountPerExam> result = QuestionTypeCountPerExam.findQuestionTypeCountPerExamEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'QuestionTypeCountPerExam' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'QuestionTypeCountPerExam' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void QuestionTypeCountPerExamIntegrationTest.testFlush() {
        QuestionTypeCountPerExam obj = dod.getRandomQuestionTypeCountPerExam();
        Assert.assertNotNull("Data on demand for 'QuestionTypeCountPerExam' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QuestionTypeCountPerExam' failed to provide an identifier", id);
        obj = QuestionTypeCountPerExam.findQuestionTypeCountPerExam(id);
        Assert.assertNotNull("Find method for 'QuestionTypeCountPerExam' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyQuestionTypeCountPerExam(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'QuestionTypeCountPerExam' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void QuestionTypeCountPerExamIntegrationTest.testMergeUpdate() {
        QuestionTypeCountPerExam obj = dod.getRandomQuestionTypeCountPerExam();
        Assert.assertNotNull("Data on demand for 'QuestionTypeCountPerExam' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QuestionTypeCountPerExam' failed to provide an identifier", id);
        obj = QuestionTypeCountPerExam.findQuestionTypeCountPerExam(id);
        boolean modified =  dod.modifyQuestionTypeCountPerExam(obj);
        Integer currentVersion = obj.getVersion();
        QuestionTypeCountPerExam merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'QuestionTypeCountPerExam' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void QuestionTypeCountPerExamIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'QuestionTypeCountPerExam' failed to initialize correctly", dod.getRandomQuestionTypeCountPerExam());
        QuestionTypeCountPerExam obj = dod.getNewTransientQuestionTypeCountPerExam(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'QuestionTypeCountPerExam' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'QuestionTypeCountPerExam' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'QuestionTypeCountPerExam' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void QuestionTypeCountPerExamIntegrationTest.testRemove() {
        QuestionTypeCountPerExam obj = dod.getRandomQuestionTypeCountPerExam();
        Assert.assertNotNull("Data on demand for 'QuestionTypeCountPerExam' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'QuestionTypeCountPerExam' failed to provide an identifier", id);
        obj = QuestionTypeCountPerExam.findQuestionTypeCountPerExam(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'QuestionTypeCountPerExam' with identifier '" + id + "'", QuestionTypeCountPerExam.findQuestionTypeCountPerExam(id));
    }
    
}
