// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package medizin.server.domain;

import java.util.List;
import medizin.server.domain.StaticToAssesment;
import medizin.server.domain.StaticToAssesmentDataOnDemand;
import medizin.server.domain.StaticToAssesmentIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect StaticToAssesmentIntegrationTest_Roo_IntegrationTest {
    
    declare @type: StaticToAssesmentIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: StaticToAssesmentIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: StaticToAssesmentIntegrationTest: @Transactional;
    
    @Autowired
    private StaticToAssesmentDataOnDemand StaticToAssesmentIntegrationTest.dod;
    
    @Test
    public void StaticToAssesmentIntegrationTest.testCountStaticToAssesments() {
        Assert.assertNotNull("Data on demand for 'StaticToAssesment' failed to initialize correctly", dod.getRandomStaticToAssesment());
        long count = StaticToAssesment.countStaticToAssesments();
        Assert.assertTrue("Counter for 'StaticToAssesment' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void StaticToAssesmentIntegrationTest.testFindStaticToAssesment() {
        StaticToAssesment obj = dod.getRandomStaticToAssesment();
        Assert.assertNotNull("Data on demand for 'StaticToAssesment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StaticToAssesment' failed to provide an identifier", id);
        obj = StaticToAssesment.findStaticToAssesment(id);
        Assert.assertNotNull("Find method for 'StaticToAssesment' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'StaticToAssesment' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void StaticToAssesmentIntegrationTest.testFindAllStaticToAssesments() {
        Assert.assertNotNull("Data on demand for 'StaticToAssesment' failed to initialize correctly", dod.getRandomStaticToAssesment());
        long count = StaticToAssesment.countStaticToAssesments();
        Assert.assertTrue("Too expensive to perform a find all test for 'StaticToAssesment', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<StaticToAssesment> result = StaticToAssesment.findAllStaticToAssesments();
        Assert.assertNotNull("Find all method for 'StaticToAssesment' illegally returned null", result);
        Assert.assertTrue("Find all method for 'StaticToAssesment' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void StaticToAssesmentIntegrationTest.testFindStaticToAssesmentEntries() {
        Assert.assertNotNull("Data on demand for 'StaticToAssesment' failed to initialize correctly", dod.getRandomStaticToAssesment());
        long count = StaticToAssesment.countStaticToAssesments();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<StaticToAssesment> result = StaticToAssesment.findStaticToAssesmentEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'StaticToAssesment' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'StaticToAssesment' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void StaticToAssesmentIntegrationTest.testFlush() {
        StaticToAssesment obj = dod.getRandomStaticToAssesment();
        Assert.assertNotNull("Data on demand for 'StaticToAssesment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StaticToAssesment' failed to provide an identifier", id);
        obj = StaticToAssesment.findStaticToAssesment(id);
        Assert.assertNotNull("Find method for 'StaticToAssesment' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyStaticToAssesment(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'StaticToAssesment' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StaticToAssesmentIntegrationTest.testMergeUpdate() {
        StaticToAssesment obj = dod.getRandomStaticToAssesment();
        Assert.assertNotNull("Data on demand for 'StaticToAssesment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StaticToAssesment' failed to provide an identifier", id);
        obj = StaticToAssesment.findStaticToAssesment(id);
        boolean modified =  dod.modifyStaticToAssesment(obj);
        Integer currentVersion = obj.getVersion();
        StaticToAssesment merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'StaticToAssesment' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StaticToAssesmentIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'StaticToAssesment' failed to initialize correctly", dod.getRandomStaticToAssesment());
        StaticToAssesment obj = dod.getNewTransientStaticToAssesment(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'StaticToAssesment' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'StaticToAssesment' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'StaticToAssesment' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void StaticToAssesmentIntegrationTest.testRemove() {
        StaticToAssesment obj = dod.getRandomStaticToAssesment();
        Assert.assertNotNull("Data on demand for 'StaticToAssesment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StaticToAssesment' failed to provide an identifier", id);
        obj = StaticToAssesment.findStaticToAssesment(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'StaticToAssesment' with identifier '" + id + "'", StaticToAssesment.findStaticToAssesment(id));
    }
    
}
